### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::3001

### ISSUE THREAD

**Issue by vvmspace** [viasite/site-audit-seo#1]
JSON file: http://localhost:3001/data.json

Dev viewer: http://localhost:3000/?url=http://localhost:3001/data.json

Online viewer: https://viasite.github.io/site-audit-seo-viewer/?url=http://localhost:3001/data.json

Finish: 7.9 mins (0.14 sec per page)
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.listen (/usr/local/lib/node_modules/site-audit-seo/node_modules/express/lib/application.js:618:24)
    at module.exports (/usr/local/lib/node_modules/site-audit-seo/src/actions/startViewer.js:43:9)
    at finishScan (/usr/local/lib/node_modules/site-audit-seo/src/scrap-site.js:476:13)
    at async tryFinish (/usr/local/lib/node_modules/site-audit-seo/src/scrap-site.js:491:7)
    at async module.exports (/usr/local/lib/node_modules/site-audit-seo/src/scrap-site.js:509:3)
    at async start (/usr/local/lib/node_modules/site-audit-seo/src/index.js:217:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3001
}

**Comment by popstas** [comment]
It serve `data.json` after scan. Only one instance can obtain port 3001.
